'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CLIENTES
    Public Property IDCLIENTE As Integer
    Public Property NOMBRE As String
    Public Property APELLIDO As String
    Public Property DIRECCION As String
    Public Property SEXO As String
    Public Property CIUDAD As String
    Public Property CODIGOPOSTAL As Nullable(Of Integer)
    Public Property EMAIL As String
    Public Property NUMTELEFONO As String

End Class
