'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DBCOMERCIALEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DBCOMERCIALEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property CLIENTES() As DbSet(Of CLIENTES)
    Public Overridable Property EMPLEADOS() As DbSet(Of EMPLEADOS)
    Public Overridable Property EMPRESA() As DbSet(Of EMPRESA)
    Public Overridable Property PRODUCTO() As DbSet(Of PRODUCTO)
    Public Overridable Property PROVEEDORES() As DbSet(Of PROVEEDORES)

End Class
