'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PRODUCTO
    Public Property IDPRODUCTO As Integer
    Public Property NOMBRE As String
    Public Property Descripcion As String
    Public Property PRECIO_UNITARIO As Nullable(Of Decimal)
    Public Property Stock As Integer

End Class
