'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PROVEEDORES
    Public Property IDPROVEEDOR As Integer
    Public Property PROVEEDOR As String
    Public Property CONTACTO As String
    Public Property TELEFONO As String
    Public Property DIRECCION As String
    Public Property ESTATUS As String

End Class
